= *Scrimmage Reward Program*

*Overview*

Scrimmage Reward Program is a Java library designed to manage and track reward programs for various applications. It provides a flexible and easy-to-use API for creating, updating, and managing user rewards, points, and redemption processes.


*Features*

User Management: Get User Token.
Reward Points System: Assign, update, and track reward points for users.
Notifications: Check server up/down status.

*Modules*

1. Spring Boot Module

2. Core Java Module

**Spring Boot Module**

    <dependency>
        <groupId>com.scrimmage</groupId>
        <artifactId>spring</artifactId>
        <version>0.0.1</version>
    </dependency>

**Core Module**

    <dependency>
        <groupId>com.scrimmage</groupId>
        <artifactId>core</artifactId>
        <version>0.0.1</version>
    </dependency>

Check sample app *demo-spring*(for spring module) and *demo-core*(for core module)

**Create Events **


**Core Java **

      new ScrimmageRewardContainer(ScrimmageConfig
        .builder()
        .namespace("")
        .privateKey("")
        .apiServerEndpoint("")
        .build()).getApi().getUserToken(tokenOption);

*Spring:*


Create multiple bean provided in demo spring application.

Have a good day :)